### ISSUE TITLE
O uso da lib pode ser barrado? 

### ISSUE THREAD

**Issue by ewertonrfd** [wansleynery/SankhyaJX#2]
Boa tarde,
Atualmente estou utilizando java para fazer algumas personalizações no sankhya, só que meu dia a dia mesmo utilizo mais JS
Se eu utilizar a lib pode ter alguma chance de para de funcionar no sankhya?
Eu pensei que por seu js mesmo não deveria para de funcionar

Mas só confirmando mesmo

Obrigado desde já pela atenção

**Comment by wansleynery** [comment]
Fala, grande @EwertonDutra.

Cara, então, Eu busco trazer o máximo de compatibilidade e estabilidade da biblioteca para a plataforma Sankhya. Se houver alguma mudança na modelagem como operam lá, vou tentar desenvolver uma melhoria, correção ou implementação.
Entenda que, essa biblioteca, na verdade, foi desenvolvida para ser de uso profissional para Mim, mas achei ela tão util e estável que quis compartilhar com o pessoal que tem dificuldades também, justamente para simplificar processos e facilitar o desenvolvimento.

Espero que tenhamos mais uns bons anos e mais coisas legais para poder utilizar no Sankhya.

Abração e bons códigos!

**Comment by EwertonDutra** [comment]
> Fala, grande @EwertonDutra.
> 
> Cara, então, Eu busco trazer o máximo de compatibilidade e estabilidade da biblioteca para a plataforma Sankhya. Se houver alguma mudança na modelagem como operam lá, vou tentar desenvolver uma melhoria, correção ou implementação. Entenda que, essa biblioteca, na verdade, foi desenvolvida para ser de uso profissional para Mim, mas achei ela tão util e estável que quis compartilhar com o pessoal que tem dificuldades também, justamente para simplificar processos e facilitar o desenvolvimento.
> 
> Espero que tenhamos mais uns bons anos e mais coisas legais para poder utilizar no Sankhya.
> 
> Abração e bons códigos!

Muito bom a iniciativa
Só mesmo pensei nessa questão  

Mas assim que tiver uma próxima personalização vou procurar fazer com js usando a lib
Achei bem legal
Estava querendo fazer até eventos programados com ela 😃

Valeu

**Comment by wansleynery** [comment]
Caso tenha algum problema posterior, pode criar um novo ticket, amigo.
